#!/usr/bin/env node

/**
 * Postinstall script to fix missing expo-router assets
 * Creates modal.module.css if it doesn't exist
 */

const fs = require('fs');
const path = require('path');

try {
  const assetsDir = path.join(__dirname, '..', 'node_modules', 'expo-router', 'assets');
  const cssFile = path.join(assetsDir, 'modal.module.css');

  // Create directory if it doesn't exist
  if (!fs.existsSync(assetsDir)) {
    fs.mkdirSync(assetsDir, { recursive: true });
    console.log('Created expo-router assets directory');
  }

  // Create CSS file if it doesn't exist
  if (!fs.existsSync(cssFile)) {
    const cssContent = `/* Modal styles for expo-router web modals */
/* Auto-generated by postinstall script */

.modal {
  /* Styles are handled by React Native Web */
}
`;
    fs.writeFileSync(cssFile, cssContent, 'utf8');
    console.log('Created modal.module.css for expo-router');
  }

  console.log('✅ Postinstall completed successfully');
} catch (error) {
  console.warn('⚠️  Postinstall warning:', error.message);
  // Don't fail the install if this doesn't work
  process.exit(0);
}

